stages:
#  - maven-install
#  - docker-build
#  - deploy
  - argocd


#variables:
#  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

#image: maven:3.3.9-jdk-8
#
#cache:
#  paths:
#    - .m2/repository
#
#maven-install:
#  stage: maven-install
#  script:
#    - 'mvn install'
#    - 'ls .m2/repository'
#  tags:
#    - myk8s
#
#docker-build:
#  # Official docker image.
#  image: docker:latest
#  variables:
#    CI_REGISTRY_USER: fanchao1510@sina.com
#    CI_REGISTRY_PASSWORD: fc18650423218
#    CI_REGISTRY: registry.cn-hangzhou.aliyuncs.com
#    CI_REGISTRY_IMAGE: registry.cn-hangzhou.aliyuncs.com/fc277073030/spring-demo:$CI_COMMIT_REF_SLUG
#  stage: docker-build
#  services:
#    - docker:dind
#  before_script:
#    - docker ps
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#  script:
#    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
#    - docker push "$CI_REGISTRY_IMAGE"
#  only:
#    - master
#  tags:
#    - myk8s

#deploy:
#  image: lachlanevenson/k8s-kubectl:v1.20.1
#  services:
#    - name: docker:latest
#  stage: deploy
#  script:
#    - kubectl get pod -A
#    - docker version

#  tags:
#    - myk8s

argocd:
  stage: argocd
  image: alpine/git
  variables:
    CI_JOB_TOKEN: zYYn8MnU7r4WdCdwghpB
  script:
    - git clone http://root:${CI_JOB_TOKEN}@192.168.3.29/devops/env-dev.git
    - ls
#    - kustomize build .
  tags:
    - myk8s
